server {
    listen 80;
    server_name goose-notes.duckdns.org;
    # return 301 https://$host$request_uri;

    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://gateway:8080;
    }
}
